### ISSUE TITLE
Maintaining apps for downstream framework consumers

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector-test-framework#218]
aws-otel-java-instrumentation currently uses this test framework with springboot and spark apps. Currently the build is failing

https://github.com/aws-observability/aws-otel-java-instrumentation/runs/1745962540?check_suite_focus=true

From what I can tell, it is because the test framework is expecting a new `totalApiBytes` metric which we hadn't implemented yet. I'm wondering, when adding new validations, can we make sure to propagate the changes to the other `aws-observability` repositories?

Also, I wonder if the spark app can be removed from this repository since `aws-otel-java-instrumentation` contains a similar app too. There doesn't seem to be a reason to maintain both apps, and I think it's something we wanted to avoid.

**Comment by wyTrivail** [comment]
i reckon this change was introduced by https://github.com/aws-observability/aws-otel-test-framework/commit/a4ec8b46458fe0aee03e2235c0e01e77cab14738, it changed the metric validation template: https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/validator/src/main/resources/expected-data-template/defaultExpectedMetric.mustache which is also used in https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/validator/src/main/resources/validations/spark-otel-trace-metric-validation.yml#L6, to resolve this shortly, we can use a different metric template named "enhanced_metric_template".  To resolve this issue in long term, we should unify the sample app in one place. 

And yes we need to find a way to prevent it from breaking testing on all the repos (actually i checked that before merging but i definitely neglected some of them), which makes me feel an automatic checking is needed. We need to introduce a workflow on pull request which loop through all the validation template.

And yes for duplication on the sample apps, we can remove it with some code changes. We need to support a hybrid way so that sample app could be either in framework repo(local) for the sample apps like statsd, zipkin and other repos(remote) for the clients under our control.  

Below are the changes we need to make:

1. Remove the sample app from framework repo, we will need to change some code as today we can just [specify the sample app's name](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/common.tf#L14) and then the framework will be able to find the sample app image/source code, the [fetching](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/ec2/main.tf#L65) the [building](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/imagebuild/main.tf#L55) part need some changes. 

2. Override the sample app in https://github.com/aws-observability/aws-otel-java-instrumentation since we just added some enhancement onto the spark sample app.  Maybe this is what we can do in short.


regarding this issue, can @shaochengwang and @mxiamxia follow up? thx.

**Comment by shaochengwang** [comment]
Rolling out a quick fix https://github.com/aws-observability/aws-otel-test-framework/pull/220

**Comment by wyTrivail** [comment]
https://github.com/aws-observability/aws-otel-java-instrumentation/runs/1745962540?check_suite_focus=true succeed after rerun.

**Comment by vasireddy99** [comment]
Considering the both action items are implemented. closing the issue
