### ISSUE TITLE
AWS EC2 start_collector failure

### ISSUE THREAD

**Issue by pmm-sumo** [aws-observability/aws-otel-collector-test-framework#324]
I have followed the instruction for running the test cases (which worked more or less locally or on EKS). However, when trying to run on EC2, I am getting following error:

Command to execute:
```
$ /usr/local/bin/terraform apply -var="aoc_version=v0.11.0" -var "testcase=../testcases/otlp_http_exporter_trace_mock" -var-file="../testcases/otlp_http_exporter_trace_mock/parameters.tfvars"
```

Also tried providing `-var="aoc_image_repo=466880462355.dkr.ecr.us-west-2.amazonaws.com/pmm-test/awscollector"` but it did not change anything

```

null_resource.setup_sample_app_and_mock_server[0] (remote-exec): Creating tmp_mocked_server_1 ... done
null_resource.setup_sample_app_and_mock_server[0] (remote-exec):
null_resource.setup_sample_app_and_mock_server[0]: Creation complete after 1m52s [id=1200557390540071755]
╷
│ Error: remote-exec provisioner error
│
│   with null_resource.start_collector[0],
│   on main.tf line 277, in resource "null_resource" "start_collector":
│  277:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1264421553.sh": Process exited with status 1
```

**Comment by vasireddy99** [comment]
Sorry for delayed response, I assume you have tried these [steps](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/run-testing-framework.md#22-run-in-ec2) for running the test casess. Since i think a lot might have been changed from this issue creation. Requesting to please try to see if the issue still exists.


Please reopen this issue if the issue still exists.
